### ISSUE TITLE
Select label(s) to fetch from github API

### ISSUE THREAD

**Issue by izifortune** [izifortune/Hacktoberfest-event-dashboard#5]
### Description

Pass the github label(s) to filter issues and pull requests, in our case hacktoberfestDublin, as a configuration in gatsby-config. Future events can easily change the label to have a personalised dashboard

**Comment by Goran216** [comment]
I am going to start working on this.

**Comment by Goran216** [comment]
Hey @izifortune could you please open it again. Looks like gatsby doesn't accept the way I put label in gatsby-config.
